### PR TITLE
Improve mobile view

### PR DESCRIPTION
**Pull request by DougInAMug**
This pull request improves the view of pages on screen with widths < ~500 px. Currently a significant amount of content overflows off the right hand side:

signal-2023-04-03-175648

(I would be happy to work on the links section, which still overflows, but I would only feel comfortably doing so with `flex`)

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Thanks for the PR!

What do you mean by "flex"?

**Comment by DougInAMug** [comment]
[Flexbox](https://developer.mozilla.org/en-US/docs/Glossary/Flex), `display: flex`. It's relatively new, but old enough to have pretty high adoption by now.

**Comment by ThomasWaldmann** [comment]
@DougInAMug ah, ok. Does it break in worse-than-now ways if a browser does not know it yet?

**Comment by DougInAMug** [comment]
I just did a quick test giving an invalid `display` attribute value, and the browser just ignored it (i.e. no change). Since this isn't affecting `visibility` at all, nothing should ever be hidden... MDN confirms not-worse-than-now fallback:

> If the browser supports Grid Layout it will display the grid view, if not it ignores the display: grid and related properties and the floated layout is used.

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Supporting_Older_Browsers#falling_back_from_grid_to_float

caniuse puts support for flexbox at 99.05% for what it's worth.

**Comment by ThomasWaldmann** [comment]
Sounds good!

**Comment by DougInAMug** [comment]
I went ahead and prevented the links from overflowing. I switched to hover effect to background shadow. It would be possible to keep it as changing font-weight to bold, but it would complexify markup a bit. I also changed ems -> rems - for more predictable sizing.

**Comment by DougInAMug** [comment]
... and would you be interested in further polishing of the website?

**Comment by ThomasWaldmann** [comment]
@DougInAMug Very interested!

As you have seen, the site is not very polished yet - mainly due to no one good with CSS and design working on it.

If we could do small, incremental improvements to the site, that would be great.

My personal preference is simple and pretty, if that helps. :-)

Maybe we can keep this PR relatively small, finish and merge it and see how it goes?

**Comment by DougInAMug** [comment]
>  small, incremental improvements  ... simple and pretty

It sounds like we're on the same page :)

I can't think of anything more I'd want to add to this PR, since I believe it fixes the major mobile related issues. Unless there's something you'd like changed, feel free to merge.

**Comment by DougInAMug** [comment]
Hey @ThomasWaldmann it seems like a building action still needs to be performed https://github.com/borgbackup/borgbackup.github.io/actions

**Comment by ThomasWaldmann** [comment]
Strange, usually that's automatic.

**Pull request merged**
