### PR TITLE
fixed broken links

### PR DESCRIPTION
**Pull request by MichaelRupertDev**
Fixing issues reported in 

https://github.com/borgbackup/borgbackup.github.io/issues/23#issuecomment-348707284

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Thanks for fixing this. Looks good, just remove the trailing blanks you have accidentally added, see there:

https://github.com/borgbackup/borgbackup.github.io/pull/24/files

**Comment by MichaelRupertDev** [comment]
Should be fixed :)

**Comment by ThomasWaldmann** [comment]
let's see! :)

**Comment by ThomasWaldmann** [comment]
didn't work. you need to make the PR against "source".

**Comment by ThomasWaldmann** [comment]
You still need to redo the PR against "source".

**Comment by ThomasWaldmann** [comment]
ping?

**Pull request merged**
